CREATE TABLE cosplays (id INTEGER PRIMARY KEY, item TEXT, materials TEXT, price INTEGER, amount INTEGER, lastest_reviews TEXT);



INSERT INTO cosplays VALUES (1, "aaron cosplay", "human flesh, i mean.. polyerter", 99.99, 69, "tf is this man?");



insert into cosplays values (2, "better yae miko cosplay", "polyester", 100.99, 68, "hot");



insert into cosplays values (3, "ayaka cosplay", "polyerter and carton (not made with metal)", 89.99, 55, "kina trash, the supossed to be metal is carton");



insert into cosplays values (4, "batman", "cotton, polyerster, leather", 264.99, 167, "whoa shit man, IM BATMAN");



insert into cosplays values (5, "primogem", "polyerter", 54.99, 56, "best gift i ever got someone");



insert into cosplays values (6, "zhongli cosplay", "polyerter", 109.99, 34, "slodify ;)" );



insert into cosplays values (7, "spoederman", "leather, polyester", 224.99, 230, "ehhehe get webbed");



insert into cosplays values (8, "joe_biden", "trump's wall", 23.99, 998, "bro dont buy this i leteraly just got a brick i can step into");

 

insert into cosplays values (9, "darian cosplay", "hoodies", 59.99, 266, "i mean its a pretty good hoodie bro");



insert into cosplays values (10, "joe", "unspeciefied materials", 665.99, "full stock", "w-w-w-why does it look like my mother and why is it so.. sogy? where is my mother!?");



insert into cosplays values (11, "german", "...", 23.99, 998, "bro dont buy this i leteraly just got a brick i can step into");

insert into cosplays values (12, "Alex (from minecraft)", "carton and polyester", 66.99, 768, "its pretty hard to move around and it gets very hot inside bt iot looks pretty good");

insert into cosplays values (13, "The Hashibira Inosuke costume", "cotton, iron, wood, polyester", 230.99, 653, "omg this is genius");

insert into cosplays values (14, "Kanroji Mitsuri", "polyester", 159.99, 885, "holy shit it has tities included!? i am woman now");

insert into cosplays values (15, "mario", "polyester", 79.99, 485, "why doesnt it say its for obese people? i mean its huge bro");
